KEYWORDS = [
    "about", "about-us", "company", "company-profile",
    "who-we-are", "profile", "history", "mission", "vision",
    "team", "management", "leadership",
    "contact", "contact-us", "location", "headquarters",
    "services", "solutions", "products",
    "industries", "clients", "partners", "references",
    "certificates", "quality",

    "o-nas", "o-podjetju", "podjetje", "druzba", "družba",
    "kdo-smo", "predstavitev", "zgodovina",
    "poslanstvo", "vizija", "vrednote",
    "ekipa", "vodstvo", "uprava",
    "kontakt", "lokacija", "naslov", "sedez", "sedež",
    "storitve", "resitve", "rešitve",
    "izdelki", "dejavnost", "dejavnosti",
    "partnerji", "reference", "certifikati", "kakovost","kontaktirajte-nas",
    "predstavitev-podjetja",
    "o-druzbi",
    "o-družbi",
    "nasa-zgodba",
    "naša-zgodba",
    "kdo-smo-mi",
    "naslov-podjetja",
    "ponudba",
    "prodajni-program",
    "program",
    "dejavnost-podjetja",
    "opis-podjetja",
    "o-podjetju",
    "o-nasem-podjetju",
    "o-našem-podjetju",

    "o-nama", "o-kompaniji", "kompanija", "tvrtka",
    "preduzece", "preduzeće", "drustvo", "društvo",
    "tko-smo", "ko-smo", "misija", "povijest", "istorija",
    "rukovodstvo", "adresa", "sjediste", "sjedište",
    "usluge", "proizvodi", "delatnost", "djelatnost",

    "uber-uns", "ueber-uns", "unternehmen", "firma",
    "firmenprofil", "wer-wir-sind", "geschichte",
    "werte", "mitarbeiter", "geschaftsfuhrung",
    "geschäftsführung", "standort", "adresse",
    "hauptsitz", "dienstleistungen", "leistungen",
    "losungen", "lösungen", "produkte",
    "branchen", "kunden", "referenzen", "zertifikate",
    "qualitat", "qualität",

    "chi-siamo", "azienda", "societa", "società",
    "impresa", "profilo-aziendale", "storia",
    "missione", "visione", "valori",
    "direzione", "contatti", "sede", "indirizzo",
    "servizi", "soluzioni", "prodotti",
    "clienti", "referenze", "certificazioni",

    "a-propos", "qui-sommes-nous", "entreprise",
    "societe", "société", "compagnie",
    "presentation", "présentation", "histoire",
    "valeurs", "equipe", "équipe", "direction",
    "adresse", "siege", "siège",
    "services", "solutions", "produits",
    "clients", "partenaires", "références",

    "sobre-nosotros", "quienes-somos", "empresa",
    "compañía", "sociedad", "perfil-empresa",
    "historia", "mision", "misión", "vision", "visión",
    "valores", "equipo", "contacto", "sede",
    "servicios", "soluciones", "productos",
    "clientes", "referencias",

    "over-ons", "wie-zijn-wij", "bedrijf",
    "onderneming", "bedrijfsprofiel",
    "geschiedenis", "missie", "visie",
    "directie", "hoofdkantoor", "diensten",
    "oplossingen", "producten", "klanten",

    "o-nas", "kim-jestesmy", "kim-jesteśmy",
    "firma", "przedsiębiorstwo", "spółka",
    "historia", "misja", "wizja",
    "zarząd", "siedziba", "usługi",
    "produkty", "klienci", "referencje",

    "kdo-jsme", "kto-sme", "společnost", "spoločnosť",
    "firma", "historie", "historia",
    "vedení", "vedenie", "sídlo",
    "služby", "produkty", "zákazníci",
]